/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package it.daddo.agenda.gui.items;

/**
 *
 * @author Anna
 */
public class ItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemPanel
     */
    public ItemPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_icon = new javax.swing.JLabel();
        jLabel_titolo = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton_update = new javax.swing.JButton();
        jButton_DELATE = new javax.swing.JButton();

        jLabel_icon.setText("jLabel1");
        jLabel_icon.setMaximumSize(new java.awt.Dimension(48, 48));
        jLabel_icon.setMinimumSize(new java.awt.Dimension(48, 48));
        jLabel_icon.setPreferredSize(new java.awt.Dimension(48, 48));

        jLabel_titolo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_titolo.setText("jLabel1");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update32.png"))); // NOI18N
        jButton_update.setFocusable(false);
        jButton_update.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_update.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_update);

        jButton_DELATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete32.png"))); // NOI18N
        jButton_DELATE.setFocusable(false);
        jButton_DELATE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_DELATE.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton_DELATE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel_titolo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_titolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DELATE;
    private javax.swing.JButton jButton_update;
    private javax.swing.JLabel jLabel_icon;
    private javax.swing.JLabel jLabel_titolo;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
